name: Dockerfile

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 8 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . -t ghcr.io/Root-DE/Applied-Cybersecurity/scan:latest
    - name: Push
      run: docker push ghcr.io/Root-DE/Applied-Cybersecurity/scan:latest
    

