name: Dockerfile

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: docker build . -t ghcr.io/root-de/applied-cybersecurity/scan:latest
    - name: Push
      run: docker push ghcr.io/root-de/applied-cybersecurity/scan:latest
    

